name: Deploy to Azure App Service

on:
  push:
    branches:
      - master  # 或您的主分支名稱，例如 main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout 程式碼
      uses: actions/checkout@v3
    
    - name: 設定 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: 安裝相依套件
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # 如果需要運行測試
    
    - name: 運行測試 (可選)
      run: |
        pytest
      continue-on-error: true  # 測試失敗也繼續部署
    
    - name: 登入 Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # 需要在 GitHub 設定中添加此機密
    
    - name: 部署到 Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ptt-web-crawler-dhh5afbwd8b2caew'  # 您的 App Service 名稱
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # 需要在 GitHub 設定中添加此機密
        package: .  # 部署的內容
    
    - name: 部署結果
      run: |
        echo "部署到 ${{ steps.deploy-to-webapp.outputs.webapp-url }} 完成"
